### ISSUE TITLE
Add static string variant

### ISSUE THREAD

**Issue by Koxiaet** [rust-analyzer/smol_str#22]
Add a new variant which contains a `&'static str` to allow easily creating a smol str at compile time.

**Comment by jD91mZM2** [comment]
Why? `SmolStr::new` is probably already constified as a part of optimization. Maybe it should be explicitly marked as a `const` function though, in order to be able to use it in constants

**Comment by matklad** [comment]
Yeah, I've just released `0.1.17` with `const fn new_inline(text: &str) -> SmolStr`. If you need to handle long const stirng, I suggest sticking with just `&'static str`, or maybe wrapping `SmolStr` into `once_cell::Lazy`.
