### ISSUE TITLE
error[E0658]: `while` is not allowed in a `const fn`

### ISSUE THREAD

**Issue by galich** [rust-analyzer/smol_str#25]
While running `cargo install cargo-audit --force` with Rust 1.44 we are getting following error in smol_str:

```
error[E0658]: `while` is not allowed in a `const fn`
  --> C:\Users\serg\.cargo\registry\src\github.com-1ecc6299db9ec823\smol_str-0.1.17\src\lib.rs:58:9
   |
58 | /         while i < text.len() {
59 | |             buf[i] = text.as_bytes()[i];
60 | |             i += 1
61 | |         }
   | |_________^
   |
   = note: see issue #52000 <https://github.com/rust-lang/rust/issues/52000> for more information
```

Is there a minimum supported version for smol_str? We really love `cargo audit` and we can't go Rust 1.45+ due to performance issues.

**Comment by matklad** [comment]
Yep, the MSRV is latest stable. I've pushed commit that clarifies that. 

https://github.com/bodil/smartstring is an interesting alternative crate in this space, which might offer more stable MSRV guarantees.

**Comment by galich** [comment]
Thanks @matklad , fair enough.

We need fresh cargo audit and we depend on smol_str indirectly. Unfortunately we can't upgrade Rust to recent stable in our CI just yet. I'll bring this up with cargo audit then.

**Comment by matklad** [comment]
Note that you can always pin `smol_str` to a specific version in some `Cargo.lock`.
