### ISSUE TITLE
Add feature for Rc based heap-allocated string

### ISSUE THREAD

**Issue by mhseiden** [rust-analyzer/smol_str#30]
The use of `Arc` for heap-allocated strings is a great default, as it works as expected in many contexts. However for more specialized (guaranteed single-threaded) cases an `Rc` is sufficient. It would be great if this crate had a feature flag which enabled compiling with `Rc` instead of `Arc`, for those cases.

**Comment by Veykril** [comment]
See https://github.com/rust-analyzer/smol_str/pull/37#issuecomment-925902011
