### ISSUE TITLE
Cargo failed to select version of `smol_str`.

### ISSUE THREAD

**Issue by BratSinot** [rust-analyzer/smol_str#47]
Greetings,

I don't know where to write about this, but with `0.1.22` version, cargo sometimes refuse to build:
```
failed to select a version for the requirement `smol_str = "^0.1.22"`
candidate versions found which didn't match: 0.1.21, 0.1.20, 0.1.19, ...
location searched: crates.io index
```
But if change version on `0.1.21` (`version = "=0.1.21"`) everything build fine.

P.S. Tried clean cargo cache and clean install.

**Comment by bjorn3** [comment]
Do you have any other dependencies? Maybe some other dependency pins it to 0.1.21? Does specifying `version = "0.1.21"` without `=` work?

**Comment by Veykril** [comment]
`0.1.22` requires the latest stable cargo due to new feature we use in the `Cargo.toml`, I wonder if that might be the cause?

**Comment by BratSinot** [comment]
> `0.1.22` requires the latest stable cargo due to new feature we use in the `Cargo.toml`, I wonder if that might be the cause?

```
➜  ~ cargo --version
cargo 1.60.0 (d1fd9fe2c 2022-03-01)
```

It has worked fine, but at some point start glitching. I don't know what the cause, I tried clean cache, do clean install, rebuild whole project etc.
Also, some of my colleagues faced with same problem unexpectedly.

**Comment by c1wren** [comment]
I've just started experiencing this issue as well. I don't directly use smol_str, but I have a dependency that does and just specifies "1".

**Comment by edwin0cheng** [comment]
I had this issue before, but after I update rust `rustup update` and then it works properly.

**Comment by lnicola** [comment]
Maybe check if you have a  `rust-toolchain` file?

**Comment by Veykril** [comment]
So I think this is due to the new use of the cargo feature. I wonder if we should yank this release and make it a `0.2.0` instead, as this seems to break everyone with an older cargo

**Comment by Veykril** [comment]
I went ahead and yanked the version, we should consider doing a `0.2.0` release for that change

**Comment by nico-abram** [comment]
I just ran into this on `cargo 1.59.0 (49d8809dc 2022-02-10)` so I'm not sure yanking helped

Updating to `cargo 1.60.0 (d1fd9fe2c 2022-03-01)` fixed it.

**Comment by Veykril** [comment]
Ye that is a shame, will publish a new version that is equal to 0.1.21 then, and if that doesn't fix it I guess that is just unfortunate :/

**Comment by matklad** [comment]
Note that the crates policy is

> Bumping MSRV is not considered a semver-breaking change.
