### ISSUE TITLE
Changelog / release notes

### ISSUE THREAD

**Issue by alexheretic** [rust-analyzer/smol_str#56]
A breaking bump to `0.2.0` was published recently. However, I can't see any notes on why in
* github releases / tag text
* CHANGELOG.md file
* README.md file

Looking at the commits it seems feature optional changes & `From` impls are technically breaking though should be fine for most usages. But having to read commit messages for this isn't ideal as a user of this lib.

Is there somewhere else I should be looking?

**Comment by Veykril** [comment]
Ah sorry, I forgot to update those, Will do that in a bit, what roughly changed is is that the `serde` dependency is no longer pulled in by default (it is now a proper optional dependency) and the `From` impls have changed, https://github.com/rust-analyzer/smol_str/commit/2a2b7df56861d98307b83ef8f8861e01bdfb9142, they are less general now (no longer anything that implements `AsRef<str>` is now `From`/`Into`able), this had to be done so we could offer an `AsRef<str>` impl.
