### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by jehugaleahsa** [rust-analyzer/smol_str#60]
Just looking at the docs for the first time and noticing a few readability issues with the module description:
https://github.com/rust-analyzer/smol_str/blob/7d1b60c45f565f8c55d8a4ffe2e6dc415097b253/src/lib.rs#L22

It's "therefor" instead of "therefore". 

The `::<SmolStr>` and `::<string>` doesn't show up on the crate docs either:

![image](https://github.com/rust-analyzer/smol_str/assets/1368126/575803e2-c6a8-4f35-93b7-9b7b8d59120c)

Reading this (https://github.com/rust-lang/rust/issues/18419), it sounds like you need to escape the `<` and `<` since they are HTML. Probably just `&lt;` and `&gt;`.

**Comment by Veykril** [comment]
No that was just missing a backtick see https://github.com/rust-analyzer/smol_str/pull/59 😄
