### ISSUE TITLE
Add `SmolStrBuilder` / `SmolStrBuffer`

### ISSUE THREAD

**Issue by alexheretic** [rust-analyzer/smol_str#70]
To build a `SmolStr` from parts it would be useful to have a writeable builder.

Perhaps something like
```rust
let mut result = SmolStrBuffer::new();
for part in parts {
    result.push_str(part);
}
let result = SmolStr::from(result);
```

This _almost_ already exists provided by `smol_str::Writer`, but using this has a couple of downsides
* `Writer` is hidden from docs, implying it isn't covered by stability guarantees.
* `Writer` doesn't provide infallible `push_str`, though it trivially could.

It seems straightforward to adapt `Writer` to this end.

**Comment by Veykril** [comment]
`Writer` was added as an implementation detail for the `format_smolstr!` macro, but we certainly could expose this with a nice API.
