### ISSUE TITLE
Missing tag for release v0.2.1

### ISSUE THREAD

**Issue by paolobarbolini** [rust-analyzer/smol_str#73]
Hi! While scraping our dependencies from crates.io we've found this repository to be missing the tag for release v0.2.1. Could that be added please? The exact commit id can be found from https://docs.rs/crate/smol_str/0.2.1/source/.cargo_vcs_info.json

**Comment by Veykril** [comment]
https://github.com/rust-analyzer/smol_str/releases/tag/v0.2.1
