### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by amab8901** [rust-analyzer/smol_str#76]
hi, can u add reading of env variables directly into SmolStr? thanks

**Comment by bjorn3** [comment]
The standard library only offers methods to read into `String` and `OsString`. As such the only portable option smol_str has for this is literally what you can write yourself using `std::env::var("MY_ENV_VAR").map(SmolStr::new)`. I don't see any benefit to adding such a helper to smol_str. There are an infinite number of possible such helpers and for the main use case smol_str has been designed for (rust-analyzer and other compilers) reading an env var into a SmolStr is done rarely to never.

**Comment by Veykril** [comment]
I agree with what bjorn3 said here, there isn't really any reason for us to add such a function
