### ISSUE TITLE
Build documentation with all features enabled

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-analyzer/smol_str#80]
Spotted when investigating https://github.com/bevyengine/bevy/pull/14982.

The documentation didn't show the `Serialize`/`Deserialize` implementation, and I was confused. The fix is super easy: https://github.com/Leafwing-Studios/leafwing-input-manager/blob/b2d706a499ef574803a0fd5a1d28e4d300e5292f/Cargo.toml#L82

**Comment by Veykril** [comment]
Hmm that's odd, we already have that set https://github.com/rust-analyzer/smol_str/blob/fde86a5c0cb8f397c8a59e3bb156a39fbeb754d5/Cargo.toml#L10-L12

**Comment by Veykril** [comment]
Ah, that is just not yet published that's why :)
